{{- range $cluster := .Values.applicationClusters }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.appName }}-cluster-secret-{{ $cluster.name }}
  labels:
    argocd.argoproj.io/secret-type: cluster
  namespace: {{ $.Values.appName }}-argocd
type: Opaque
stringData:
  server: {{ $cluster.address | quote }}
  name: {{ $cluster.name | quote }}
  {{- if $cluster.namespace }}
  namespaces: {{ $cluster.namespace | quote }}
  {{- end }}
  in-cluster: "true"
  config: |
    {
      "bearerToken": {{ $.Values.token | quote }},
      "tlsClientConfig": {
        "insecure": true
      }
    }
---
{{- end }}
